#pragma once
// Tranh bao gom file nhieu lan trong qua trinh bien dich

#include <string>     // Su dung kieu du lieu string
#include <ctime>      // Su dung kieu du lieu time_t de quan ly thoi gian

// Dinh nghia enum dai dien cho vai tro nguoi dung
enum class UserRole { USER, ADMIN };
// USER: nguoi dung binh thuong
// ADMIN: quan tri vien

// Lop UserAccount dai dien cho tai khoan nguoi dung
class UserAccount {
public:
    // Cac thuoc tinh cua nguoi dung
    std::string username;                 // Ten dang nhap cua nguoi dung
    std::string hashedPassword;          // Mat khau da ma hoa SHA256
    std::string fullName;                // Ho ten nguoi dung
    std::string email;                   // Dia chi email cua nguoi dung
    std::string phone;                   // So dien thoai nguoi dung
    UserRole role;                       // Vai tro cua nguoi dung (USER hoac ADMIN)
    bool isAutoGeneratedPassword;        // Co phai mat khau duoc sinh tu dong khong
    time_t createdAt;                    // Thoi gian tao tai khoan (dang UNIX timestamp)
    time_t lastLogin;                    // Thoi gian dang nhap cuoi cung
    std::string walletId;                // Ma vi lien ket voi nguoi dung

    // Constructor mac dinh
    UserAccount();

    // Constructor day du tham so de tao mot UserAccount
    UserAccount(
        const std::string& username,                   // Ten dang nhap
        const std::string& hashedPassword,             // Mat khau da ma hoa
        const std::string& fullName,                   // Ho ten nguoi dung
        const std::string& email,                      // Email nguoi dung
        const std::string& phone,                      // So dien thoai
        UserRole role,                                 // Vai tro (USER/ADMIN)
        bool isAutoGeneratedPassword,                  // Co phai mat khau tu dong khong
        time_t createdAt,                              // Thoi gian tao
        time_t lastLogin,                              // Thoi gian dang nhap cuoi
        const std::string& walletId                    // ID cua vi
    );

    // Chuyen doi doi tuong UserAccount thanh chuoi string de luu file
    std::string serialize() const;

    // Ham tao doi tuong UserAccount tu chuoi string da luu (deserialize tu file)
    static UserAccount deserialize(const std::string& data);
};
