#include "UserAccount.h"
#include <sstream>
#include <vector>
#include <iomanip>

// Constructor mac dinh: khoi tao cac gia tri ban dau
UserAccount::UserAccount()
    : role(UserRole::USER),                   // Mac dinh vai tro la USER
      isAutoGeneratedPassword(false),         // Mac dinh khong phai mat khau tu dong
      createdAt(0),                           // Thoi gian tao = 0
      lastLogin(0)                            // Thoi gian dang nhap cuoi = 0
{}

// Constructor day du tham so
UserAccount::UserAccount(
    const std::string& username,
    const std::string& hashedPassword,
    const std::string& fullName,
    const std::string& email,
    const std::string& phone,
    UserRole role,
    bool isAutoGeneratedPassword,
    time_t createdAt,
    time_t lastLogin,
    const std::string& walletId
)
    // Su dung danh sach khoi tao thanh vien (member initializer list)
    : username(username),
      hashedPassword(hashedPassword),
      fullName(fullName),
      email(email),
      phone(phone),
      role(role),
      isAutoGeneratedPassword(isAutoGeneratedPassword),
      createdAt(createdAt),
      lastLogin(lastLogin),
      walletId(walletId)
{}

// Ham chuyen doi doi tuong UserAccount thanh mot chuoi string de luu file
std::string UserAccount::serialize() const {
    std::ostringstream oss;   // Tao mot ostringstream de ghi du lieu thanh chuoi
    // Ghi cac truong du lieu, cach nhau boi dau ','
    oss << username << ',' << hashedPassword << ',' << fullName << ',' << email << ',' << phone << ','
        << static_cast<int>(role) << ','            // Chuyen enum UserRole sang so nguyen
        << isAutoGeneratedPassword << ','           // true/false se tu dong thanh 1/0
        << createdAt << ',' << lastLogin << ','     // Thoi gian UNIX timestamp
        << walletId;
    return oss.str();        // Tra ve chuoi da ghi
}

// Ham khoi phuc doi tuong UserAccount tu chuoi string (duoc doc tu file)
UserAccount UserAccount::deserialize(const std::string& data) {
    std::istringstream iss(data);      // Doc chuoi dau vao bang istringstream
    std::string token;                 // Bien tam de luu tru gia tri tach ra
    std::vector<std::string> tokens;  // Vector luu cac truong sau khi tach
    
    // Tach chuoi theo dau ','
    while (std::getline(iss, token, ',')) tokens.push_back(token);

    // Neu so truong < 10 thi khong hop le, tra ve tai khoan rong
    if (tokens.size() < 10) return UserAccount();

    UserAccount acc; // Tao doi tuong UserAccount de gan gia tri
    acc.username = tokens[0];
    acc.hashedPassword = tokens[1];
    acc.fullName = tokens[2];
    acc.email = tokens[3];
    acc.phone = tokens[4];
    acc.role = static_cast<UserRole>(std::stoi(tokens[5]));               // Chuyen string thanh UserRole
    acc.isAutoGeneratedPassword = (tokens[6] == "1");                     // Neu = "1" thi dung la true
    acc.createdAt = std::stol(tokens[7]);                                 // Chuyen sang kieu long (thoi gian)
    acc.lastLogin = std::stol(tokens[8]);                                 // Chuyen sang kieu long (thoi gian)
    acc.walletId = tokens[9];                                             // ID cua vi
    return acc;
}
